-- This file is autogenerated by matugen. Do not edit by hand.
-- Consumed by ~/.config/hypr/hyprland.lua via require("colors").
return {
    image = "{{image}}",
<* for name, value in colors *>
    {{name}} = "rgba({{value.default.hex_stripped}}ff)",
<* endfor *>
}
