general {
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Pantallas siempre encendidas - sin apagado automático por inactividad
# listener {
#     timeout = 1800
#     on-timeout = hyprctl dispatch dpms off HDMI-A-1
#     on-resume = hyprctl dispatch dpms on HDMI-A-1 && brightnessctl -r
# }
