general {
    lock_cmd = omarchy-lock-screen                         # lock screen and 1password
    before_sleep_cmd = loginctl lock-session               # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on             # evitar doble tecla al despertar
    inhibit_sleep = 3                                      # esperar a que la pantalla esté bloqueada
}

listener {
    timeout = 300                                              # 5 min: iniciar salvapantallas
    on-timeout = pidof hyprlock || omarchy-launch-screensaver  # salvapantallas si no está ya bloqueado
}

listener {
    timeout = 600                                          # 10 min: bloquear pantalla
    on-timeout = loginctl lock-session
}

listener {
    timeout = 660                                                # 11 min: apagar pantalla
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r    # encender al detectar actividad
}

listener {
    timeout = 1800                                             # 30 min: suspender sistema
    on-timeout = systemctl suspend
}
