[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x4\x1f\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x4\x1f\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x4\x1f)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x3\xae\0\0\x3\xf9\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[performance]
js_memory_limit_index=0
js_memory_limit_mb=0

[system]
confirm_on_close=false
quit_in_close=false
spellCheckLanguage=en_US
spellCheckLanguages=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\n\0\0\0\n\0\x65\0n\0_\0U\0S)
spellCheckProvisionedLocale=en_US
start_background=true
tray_icon=true
wayland=true

[website]
open_page=false
